draw<-function(){
	x11()
	plot(c(0,0),xlim=c(0,1),ylim=c(0,1),col='white',main="please click c(0,0) first then c(1,1) then the points")
	data<-data.frame(x=0,y=0)
	new<-F
	p1<-c(0.1475410,0.1743666)
	p2<-c(0.9090909,0.8569300)
	color<<-'black'
	pen<-1
	cex<-5
	prex<-0
	prey<-0
	lin<-F
	cir<-F
	rec<-F
	add<-function(a,px,py){
		if(pen!=4){lin<<-F}
		if(pen!=5){cir<<-F}
		point<-function(x,y){
			temp<-matrix(c(runif(30)),ncol=3)
			temp[,1]<-sin(temp[,1]*2*pi)*0.02*temp[,2]+px-0.01
			temp[,2]<-sin(temp[,3]*2*pi)*0.02*temp[,2]+py-0.01
			points(temp,pch=16,cex=0.8*cex/10,col=color)
		}
		line<-function(x,y){
			if(lin==F){
				prex<<-x
				prey<<-y
				lin<<-T
			}
			else{
				lines(c(x,prex),c(y,prey),type='l',lwd=5*cex/10,col=color)
				prex<<-x
				prey<<-y
				lin<<-F
			}
		}
		circle<-function(x,y){
			if(cir==F){
				prex<<-x
				prey<<-y
				cir<<-T
			}
			else{
				temp<-(1:1000)/1000
				ra<-sqrt((x-prex)^2+(y-prey)^2)
				print(ra)
				points(prex+cos(temp*2*pi)*ra,prey+sin(temp*2*pi)*ra,cex=0.8*cex/10,col=color)
				prex<<-x
				prey<<-y
				cir<<-F
			}			
		}
		rect<-function(x,y){
			if(rec==F){
				prex<<-x
				prey<<-y
				rec<<-T
			}
			else{
				lines(c(x,prex),c(prey,prey),type='l',lwd=5*cex/10,col=color)
				lines(c(x,x),c(y,prey),type='l',lwd=5*cex/10,col=color)
				lines(c(prex,prex),c(y,prey),type='l',lwd=5*cex/10,col=color)
				lines(c(x,prex),c(y,y),type='l',lwd=5*cex/10,col=color)
				prex<<-x
				prey<<-y
				rec<<-F
			}
		}
		px<-round((px-p1[1])/(p2[1]-p1[1]),3)
		py<-round((py-p1[2])/(p2[2]-p1[2]),3)
		if(px<1 & px>0 & py<1 & py>0){
			if(pen==1)points(px,py,pch=16,col=color,cex=cex/10)
			if(pen==2)point(px,py)
			if(pen==3)painting(a,px,py)
			if(pen==4)line(px,py)
			if(pen==5)circle(px,py)
			if(pen==6)rect(px,py)
		}
		return(NULL)
	}
	painting<-function(a,px,py){
		paint<-function(x,y){
			if(!(x<=1e-3 | y<=1e-3 | x>1 | y>1)){
				if(record[x*(1e+3),y*(1e+3)]==record[px*(1e+3),py*(1e+3)] & flag[x*(1e+3),y*(1e+3)]==0){
					##points(x,y,pch=15,cex=0.1,col=color)
					flag[x*(1e+3),y*(1e+3)]<<-1
					if(round(x,1)>(1e-3) & round(y,1)>(1e-3) & round(x,1)<=1-(1e-3) & round(y,1)<=1-(1e-3))if(flag[x*(1e+3),y*(1e+3)+1]==0)paint(x,y+(1e-3))
					if(round(x,1)>(1e-3) & round(y,1)>(1e-3) & round(x,1)<=1-(1e-3) & round(y,1)<=1-(1e-3))if(flag[x*(1e+3)+1,y*(1e+3)]==0)paint(x+(1e-3),y)
					if(round(x,1)>(1e-3) & round(y,1)>(1e-3) & round(x,1)<=1-(1e-3) & round(y,1)<=1-(1e-3))if(flag[x*(1e+3),y*(1e+3)-1]==0)paint(x,y-(1e-3))
					if(round(x,1)>(1e-3) & round(y,1)>(1e-3) & round(x,1)<=1-(1e-3) & round(y,1)<=1-(1e-3))if(flag[x*(1e+3)-1,y*(1e+3)]==0)paint(x-(1e-3),y)
				}
			}
		}
		px<-(px-p1[1])/(p2[1]-p1[1])
		py<-(py-p1[2])/(p2[2]-p1[2])
		px<-round(px,1)
		py<-round(py,1)
		x<-px
		y<-py
		##if(!(x<0 | y<0 | x>1 | y>1) & record[x*(1e+3),y*(1e+3)]==record[px*(1e+3),py*(1e+3)] & flag[x*(1e+3),y*(1e+3)]==0){paint(x,y)}
		return(NULL)
	}
	col<-function(K){
		K<-tolower(K)
		if(K=='r'){color<<-'red'}
		if(K=='b'){color<<-'black'}
		if(K=='g'){color<<-'green'}
		if(K=='p'){color<<-'purple'}
		if(K=='u'){color<<-'blue'}
		if(K=='y'){color<<-'yellow'}
		if(K=='o'){color<<-'orange'}
		if(K=='e'){color<<-'white'}
		if(K=='q'){pen<<-1}
		if(K=='w'){pen<<-2}
		if(K=='a'){pen<<-3}
		if(K=='l'){pen<<-4}
		if(K=='c'){pen<<-5}
		if(K=='t'){pen<<-6}
		if(K%in%as.character(1:9)){cex<<-as.numeric(K)}
		points(0,0,col='white')
	}
	getGraphicsEvent(prompt="create.reg",onMouseMove=add,onMouseDown=add,onKeybd=col)
}